#!/usr/bin/env python3
import sys
from common import meta

def main():
    key = sys.argv[1]
    if key.startswith('auth.'):
        value = meta.auth[key.removeprefix('auth.')]
    else:
        raise KeyError(key)
    print(str(value))

if  __name__ == '__main__':
    main()
