#!/usr/bin/env python3
import sys
from common import meta

def main():
    key = sys.argv[1]
    if key == 'auth.file':
        print(meta.auth['file'])
    elif key == 'auth.alg':
        print(meta.auth['alg'])
    elif key == 'auth.group':
        print(meta.auth['group'])
    elif key == 'auth.gid':
        print(str(meta.auth['gid']))
    elif key == 'auth.pwgenopts':
        print(meta.auth['pwgenopts'])
    elif key == 'auth.emaildir':
        print(meta.auth['emaildir'])
    elif key == 'auth.shell':
        print(meta.auth['shell'])
    else:
        raise Exception("unknown key " + key)

if  __name__ == '__main__':
    main()