#!/bin/bash

set -e

source "$(dirname "$0")/helpers/common.sh"

declare -a servers
if [[ -z "$1" ]]; then
    host="$(hostname)"
    readarray -t ports < <(postfix_smtp_ports)
    if [[ "${#ports[@]}" = 0 ]]; then
        echo "${cRed}ERROR${cReset} No SMTP ports found" >&2
        exit 1
    fi
    for port in "${ports[@]}"; do
        servers+=("$host:$port")
    done
else
    readarray -t servers <<< "$@"
fi

exitcode=0

for server in "${servers[@]}"; do
    echo "${cWhiteLight}Checking TLS on${cReset} ${cCyan}${server}${cReset}"
    set +e
    openssl s_client -connect "$server" \
        -verify_return_error \
        -starttls smtp <<< QUIT
    code="$?"
    set -e
    if [[ "$code" = 0 ]]; then
        echo "${cGreen}PASS${cReset} TLS passed for" \
            "${cCyan}${server}${cReset}"
    else
        exitcode="$code"
        echo "${cRed}ERROR${cReset} TLS failed for" \
            "${cYellow}${server}${cReset} with exit code ${code}"
    fi
done

if [[ "$exitcode" != 0 ]]; then
    echo "${cRed}TLS check failed!${cReset}"
fi
exit "$exitcode"