#!/bin/bash
set -e

source "$(dirname "$0")/helpers/common.sh"

dir_="$(abs "$(dirname "$0")")"
logfiles=("${APP_LOGS[@]}")

logfiles+=(backup.log)

cd /var/log
args=("$@")
tail -F "${args[@]}" "${logfiles[@]}" 2>/dev/null | "$dir_/clr"
