#!/bin/bash


FORCE_COLOR=1 source "$(dirname "$0")/helpers/common.sh"

c_date="$cCyanLight"
c_version="$cWhiteLight"
c_default="$cCyan"
c_logfile_caret="$cGrey"
c_logfile="$cBlueLight"
c_file="$cCyanLight"
c_url="$cGreen"
c_ip="$cGreen"
c_dim="$cGrey"
c_undim="$cUndim"

c_good="$cGreenLight"
c_warn="$cYellowLight"
c_title="$cMagenta"

kwi_good='(start|started|starting)'
kwi_warn='(cannot|disable|disabled)'

rst="$cReset"

chr_default='([=])'
sed -E \
-e "s/^(==> )(.*)( <==)$/${c_logfile_caret}\1${c_logfile}\2${c_logfile_caret}\3${rst}/" \
-e "s/^([0-9]{4}-[0-9]{2}-[0-9]{2})(T)([0-9]{2}:[0-9]{2}:[0-9]{2})([0-9.:-]+)/${c_date}\1${c_dim}\2${c_undim}${c_date}\3${c_dim}\4${c_undim}${c_default}/" \
-e "s/${kwi_good}/${c_good}\1${c_default}/gi" \
-e "s/${kwi_warn}/${c_warn}\1${c_default}/gi" \
-e "s/( == )(.*)/\1${c_title}\2${c_default}/" \
-e "s#([=[:space:]])(/[a-zA-Z][a-zA-Z0-9_./-]+)([:])?#\1${c_file}\2${c_default}\3#g" \
-e "s#(https?://[a-zA-Z0-9.-]+)(/.*)?#${c_url}\1\2${c_default}#g" \
-e "s/(((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))/${c_ip}\1${c_default}/g" \
-e "s/(v?[0-9]+\.[0-9]+\.[0-9.]+)/${c_version}\1${c_default}/" \
$@

#-e "s/^([0-9T:.-]+)/${c_date}\1${c_default}/" \

#c_int="$cWhite"
#-e "s/(\s[0-9]+)/${c_int}\1${c_default}/" \
