#!/bin/bash

## :===========================:
## : ANSI Code Definitions     :
## :===========================:
#C_blue="$(printf '\x1b[0;34m')"
#C_blue_b="$(printf '\x1b[1;34m')"
C_blue="$(printf '\x1B[38;2;0;128;255m')"
C_blue_b="$(printf '\x1B[38;2;0;128;255m\x1B[1m')"
C_cyan="$(printf '\x1b[0;36m')"
C_cyan_b="$(printf '\x1b[1;36m')"
C_grey_b="$(printf '\x1b[0;37m')"
C_grey="$(printf '\x1b[1;30m')"
C_green="$(printf '\x1b[0;32m')"
C_green_b="$(printf '\x1b[1;32m')"
C_magenta="$(printf '\x1b[0;35m')"
C_magenta_b="$(printf '\x1b[1;35m')"
C_orange="$(printf '\x1B[38;2;255;165;0m')"
C_orange_b="$(printf '\x1B[38;2;255;165;0m\x1B[1m')"
C_pink="$(printf '\x1B[38;2;255;192;183m')"
C_pink_b="$(printf '\x1B[38;2;255;192;183m\x1B[1m')"
C_red="$(printf '\x1b[0;31m')"
C_red_b="$(printf '\x1b[1;31m')"
C_yellow="$(printf '\x1b[0;33m')"
C_yellow_b="$(printf '\x1b[1;33m')"
C_white="$(printf '\x1b[1;37m')"
C_white_b="$(printf '\x1b[37;1m')"
C_dim="$(printf '\x1b[2m')"
C_undim="$(printf '\x1b[22m')"
C_reset="$(printf '\x1b[0m')"
## ___________________________

## :===========================:
## : Color Style Selections    :
## :===========================:
c_default="$C_cyan"
c_date="$C_cyan_b"
c_date_ms="$C_grey"
c_version="$C_white_b"
c_logfile="$C_blue_b"
c_logfile_caret="$C_grey"
c_file="$C_cyan_b"
c_url="$C_green"
c_domain="$C_blue_b"
c_ip="$C_magenta_b"
c_email="$C_magenta"
c_title="$C_orange_b"
c_good="$C_green_b"
c_neut="$C_white"
c_semi="$C_yellow"
c_notc="$C_orange"
c_warn="$C_yellow_b"
c_bad="$C_red_b"
## ___________________________

## :==========================:
## : Regexes                  :
## :==========================:

# Convention is rx_<style>[#captures][_flags][_index]
# The ~ character is used for sed command delimiter

rx_good_gi='(allowlisted|delivered| ok\b|dkim-signature field added|dkim verification successful|message accepted|no signature error|noqueue: permit'
rx_good_gi="${rx_good_gi}|pass new|pass old|passed|received-spf: pass|sender spf authorized|Trusted TLS|whitelisted)"

rx_neut_gi='(Anonymous TLS|\bconnect from\b|\bdisconnect from\b|sighup)'

rx_notc_gi='(refreshing the postfix mail system|reloading configuration|shutting down)'

rx_semi_gi='(authentication aborted|\bdisable\b|\bdisabled\b|does not resolve|failed to parse|lost connection'
rx_semi_gi="${rx_semi_gi}|received-spf: none|no signing table match|non-smtp command|unsupported protocol)"

rx_warn_gi='(domain owner discourages use of this host|no auth attempts|pregreet|untrusted tls|warning)'

rx_bad_gi='(access problem|auth failed|authentication failed|bad command|bad signature data|blacklisted|client host rejected|command not found|connection refused|denylisted'
rx_bad_gi="${rx_bad_gi}|error loading|error:|\[error]| fatal\b"
rx_bad_gi="${rx_bad_gi}|host rejected|internal error|killed with signal 15|login failed|name or service not known|no such file or directory|noqueue: reject"
rx_bad_gi="${rx_bad_gi}|password mismatch|permission denied|\breject\b|signature verification failed|sigterm|signal 15|softfail|ssl_accept error|unknown user)"

rx_date4='^([0-9]{4}-[0-9]{2}-[0-9]{2})(T)([0-9]{2}:[0-9]{2}:[0-9]{2})([0-9.:-]+)'

rx_email_g='\b([a-z0-9._+-]+@[a-z0-9._+-]+)\b'

rx_logfile3='^(==> )(.*)( <==)$'

rx_title2='( == )(.*)'

rx_file2_g='([=[:space:](])(/[a-zA-Z][a-zA-Z0-9_./-]+)([:)])?'

rx_url2_g='(https?://[a-zA-Z0-9.-]+)(/.*)?'

rx_domain2_g_1='(hostname |helo=)([a-z0-9-]+\.[a-z0-9.-]+)'
rx_domain2_g_2='([=[:space:]])([a-z0-9.-]+\.(com|org|net|edu))'

rx_ip4cidr_g='(((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])(/[0-9]{1,2})?)'

rx_version2='(v|version )([0-9]+\.[0-9]+\.[0-9.]+)'
## ___________________________

## :=====================:
## : Execute             :
## :=====================:
sed -E \
-e "s~${rx_logfile3}~${c_logfile_caret}\1${c_logfile}\2${c_logfile_caret}\3${c_default}~" \
-e "s~${rx_date4}~${c_date}\1${c_date_ms}\2${c_date}\3${c_date_ms}\4${c_default}~" \
-e "s~${rx_neut_gi}~${c_neut}\1${c_default}~gi" \
-e "s~${rx_notc_gi}~${c_notc}\1${c_default}~gi" \
-e "s~${rx_semi_gi}~${c_semi}\1${c_default}~gi" \
-e "s~${rx_good_gi}~${c_good}\1${c_default}~gi" \
-e "s~${rx_warn_gi}~${c_warn}\1${c_default}~gi" \
-e "s~${rx_bad_gi}~${c_bad}\1${c_default}~gi" \
-e "s~${rx_email_g}~${c_email}\1${c_default}~g" \
-e "s~${rx_title2}~\1${c_title}\2${c_default}~" \
-e "s~${rx_file2_g}~\1${c_file}\2${c_default}\3~g" \
-e "s~${rx_url2_g}~${c_url}\1\2${c_default}~g" \
-e "s~${rx_domain2_g_1}~\1${c_domain}\2${c_default}~g" \
-e "s~${rx_domain2_g_2}~\1${c_domain}\2${c_default}~g" \
-e "s~${rx_ip4cidr_g}~${c_ip}\1${c_default}~g" \
-e "s~${rx_version2}~\1${c_version}\2${c_default}~" \
-e "s~(status=)(sent)\b~\1${c_good}\2${c_default}~" \
-e "s~$~${C_reset}~" \
$@
