#!/bin/bash
source "$(dirname "$0")/helpers/common.sh"
shopt -s expand_aliases
if [[ -z "$ISCRON" ]]; then
    alias logger="/usr/bin/logger -t diffie"
else
    alias logger="/usr/bin/logger -t diffie-cron"
fi

if [[ -t 0 ]] && [[ -z "$ISCRON" ]]; then
    alias write="echo -e"
else
    alias write="true"
fi

log() {
    local fdn msg pfx
    local priority="$1"
    if [[ "$priority" = err ]]; then
        fdn=2
        pfx="${cRed}ERROR${cReset} "
    else
        fdn=1
    fi
    while read msg ; do
        write "$pfx$msg" >&$fdn
        logger -p "$priority" "$msg"
    done
}

run() {
    {
        _run 2>&1 1>&3 3>&- | log err
    } 3>&1 1>&2 | log notice
}

_run() {
    set -e
    local thisdir="$(abs `dirname "$0"`)"
    local confdir=`postconf -h config_directory`
    local dhdir="$confdir/ssl/dh"
    local outdir="$dhdir/$(date_path)"

    echo "Generating new dhparams for postfix"
    mkdir -pv "$dhdir"
    mkdir -v "$outdir"
    openssl dhparam -5 -check -out "$outdir/dh512.pem" 512 2>&1
    openssl dhparam -5 -check -out "$outdir/dh1024.pem" 1024 2>&1

    echo "Marking new files as active"
    pushdq "$dhdir"
    rm -f active
    ln -s "$(basename "$outdir")" active
    popdq

    postfix_reload

    if is_dovecot; then
        echo "Generating new dhparams for dovecot"
        local tmpfile="$(mktemp)"
        local dhfile="$(sed 's/<//' <<< "$(doveconf -h ssl_dh)")"
        openssl dhparam -5 -check -out "$tmpfile" 4096 2>&1
        mv "$tmpfile" "$dhfile"
        chmod 0644 "$dhfile"
        dovecot_reload
    fi
}

run