#!/bin/bash

DKIM_KEYS_DIR=/etc/opendkim/keys

dir_="$(dirname "$0")"
source "$dir_/helpers/common.sh"

set -e
shopt -s expand_aliases

alias dkey-test="$dir_/dkey-test"

usage="Usage: dkey-install [-f] [-n] DOMAIN [ID]"
help='
Install a DKIM key.

  -f, --force       Skip key verification.
  -n, --norestart   Do not restart opendkim after install.
'

log_err() {
  echo "${cRed}Error$cReset $@" >&2
}

fail() {
  log_err "$@"
  exit 1
}

soft_fail() {
  echo "$@" >&2
  exit 1
}

log_info() {
  echo "$cMagentaLight$uCaret$cReset $@"
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -h|--help) printf '%s\n%s' "$usage" "$help"; exit 0;;
    -f|--force) force=1;;
    -n|--norestart) norestart=1;;
    -*) fail "Unknown option: $1";;
    *) true;
      if [[ -z "$domain" ]]; then
        domain="$1"
      elif [[ -z "$id" ]]; then
        id="$1"
      else
        log_err "Too many arguments"
        soft_fail "$usage"
      fi;;
  esac
  shift
done

if [[ -z "$id" ]]; then
  id=$(date +"%Y%m")
fi

log_info "Installing key $id for domain $domain"

if [[ -z "$force" ]]; then
    dkey-test "$domain" "$id"
fi

resc() {
    sed -E 's~([.\*])~\\\1~g' <<<"$1"
}

format-entry() {
    local key=$1
    local value=$2
    local file=$3
    local keywidth="$(grep -E '^[^#\s].' "$file" | awk '{print $1}' | wc -L)"
    [[ "${#key}" -lt "$keywidth" ]] || keywidth="${#key}"
    awk "{printf \"%-${keywidth}s    %s\", \$1, \$2}" <<<"$key $value"
}

get-entry() {
    local keyesc="$(resc "$1")"
    local file="$2"
    grep -E "^$keyesc\s" "$file"
}

has-entrykey() {
    get-entry $@ > /dev/null
}

has-entry() {
    local keyesc="$(resc "$1")"
    local valesc="$(resc "$2")"
    local file="$3"
    grep -qE "^$keyesc\s+$valesc\$" "$file"
}

replace-entry() {
    local keyesc="$(resc "$1")"
    local entry="$2"
    local file="$3"
    sed -i -E "s~^$keyesc\s.*~$entry~" "$file"
}

keyfile="$DKIM_KEYS_DIR/$id.$domain.private"
keytable="$(opendkim -e KeyTable)"
signtable="$(opendkim -e SigningTable | sed 's~^refile:~~')"

for file in "$keyfile" "$keytable" "$signtable" ; do
    [[ -e "$file" ]] || fail "$file not found"
done

keyname="${id}_${domain}"
keyvalue="$domain:$id:$keyfile"
keyentry="$(format-entry "$keyname" "$keyvalue" "$keytable")"

if has-entrykey "$keyname" "$keytable" ; then
    if has-entry "$keyname" "$keyvalue" "$keytable" ; then
        log_info "Key table entry already present"
    else
        log_err "$(get-entry "$keyname" "$keytable")"
        fail "Key table entry present but has wrong value"
    fi
else
    log_info "Adding key table entry"
    echo "$keyentry" >> "$keytable"
    ischange=1
fi

signrule="*@$domain"
signentry="$(format-entry "$signrule" "$keyname" "$signtable")"

if has-entrykey "$signrule" "$signtable" ; then
    if has-entry "$signrule" "$keyname" "$signtable" ; then
        log_info "Signing table entry already present"
    else
        log_info "Updating existing signing table entry"
        replace-entry "$signrule" "$signentry" "$signtable"
        ischange=1
    fi
else
    log_info "Adding signing table entry"
    echo "$signentry" >> "$signtable"
    ischange=1
fi

if [[ -n "$ischange" ]]; then
    if [[ -z "$norestart" ]]; then
        log_info "Restarting opendkim"
        service_restart opendkim
    else
        log_info "Restart opendkim to activate changes"
    fi
else
    log_info "No changes made"
fi
