#!/bin/bash

usage="Usage: dkey-create [-w] [-k] [-n] DOMAIN [ID]"
help='
Create a DKIM key. If ID is not specified, defaults to current YYYYMM.

  -w, --wait       Wait for confirmation, then install the key.
  -k, --keyonly    Only update key table, but not signing table.
  -n, --norestart  Do not restart opendkim after install.
'

dir_="$(dirname "$0")"
source "$dir_/helpers/common.sh"

set -e
shopt -s expand_aliases

log_err() {
  echo "${cRed}Error$cReset $@" >&2
}

warn() {
  echo "${cYellowLight}Warn${cReset} $@" >&2
}

fail() {
  log_err "$@"
  exit 1
}

soft_fail() {
  echo "$@" >&2
  exit 1
}

log_info() {
  echo "$cMagentaLight$uCaret$cReset $@"
}

install_flags=("-f")

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -h|--help) printf '%s\n%s' "$usage" "$help"; exit 0;;
    -w|--wait) wait=1;;
    -n|--norestart|-k|--keyonly) install_flags+=("$1");;
    -*) fail "Unknown option: $1";;
    *) true;
      if [[ -z "$domain" ]]; then
        domain="$1"
      elif [[ -z "$id" ]]; then
        id="$1"
      else
        log_err "Too many arguments"
        soft_fail "$usage"
      fi;;
  esac
  shift
done

[[ -n "$id" ]] || id=$(date +"%Y%m")

[[ -n "$DKIM_KEYS_DIR" ]] || fail "DKIM_KEYS_DIR not set"

alias dkey-test="$dir_/dkey-test"
alias dkey-install="$dir_/dkey-install"

log_info "Creating key $id for domain $domain"

dkimuser="$(opendkim -e UserID)"
keyfile="$DKIM_KEYS_DIR/$id.$domain.private"
txtfile="$DKIM_KEYS_DIR/$id.$domain.txt"
valuefile="$txtfile.value"
linefile="$txtfile.line"

[[ ! -e "$keyfile" ]] || fail "$keyfile already exists"

mkdir -p "$DKIM_KEYS_DIR"

tmpdir=$(mktemp -d)
cd "$tmpdir"
opendkim-genkey -b 2048 -h rsa-sha256 -r -s "$id" -d "$domain" -v
chown "$dkimuser:$dkimuser" *
chmod 0600 *
mv "$id.private" "$keyfile"
mv "$id.txt" "$txtfile"
cd "$DKIM_KEYS_DIR"
rmdir "$tmpdir"

log_info "Created $keyfile"

# extract string from .txt, replace h=rsa-sha256 with h=sha256
sed -E \
  -e 's~^.*\( ~~' \
  -e 's~h=rsa-sha256~h=sha256~' \
  -e 's~ \)\s+; ----- DKIM.*~~' \
  -e 's~\s{2,}~~' \
  "$txtfile" \
  | tr -d '\n' \
  > "$valuefile"

tr -d '"' < "$valuefile" > "$linefile"

echo "
Create the following DNS TXT record for $domain:

Name:
$id._domainkey

Value (Route53 style):"
cat "$valuefile"
echo "


Value (single line):"
cat "$linefile"
echo

if [[ -z "$wait" ]]; then
  echo
  echo "After creating the DNS record, proceed with the following:"
fi

echo "
Test command:

  ${cWhiteLight}dkey-test $domain $id${cReset}

Install command:

  ${cWhiteLight}dkey-install $domain $id${cReset}
"

if [[ -z "$wait" ]]; then
  exit 0
fi

while true; do
  log_info "Press [return] to verify & install"
  read
  if dkey-test "$domain" "$id"; then
    break
  fi
  warn "Key test failed"
done

dkey-install "${install_flags[@]}" "$domain" "$id"
