#!/bin/bash

set -e

source "$(dirname "$0")/helpers/common.sh"

thisdir="$(abs `dirname "$0"`)"
alias metaval="$thisdir/helpers/metaval"
authdir="$(metaval auth.dir)"
pwdfile="$authdir/users.passwd"
alg="$(metaval auth.alg)"

username="$1"
if [[ -z "$username" ]] || [[ ! -z "$2" ]] && [[ "$2" != "--stdin" ]]; then
    echo "Usage: email-passwd <username> [--stdin]" >&2
    exit 1
fi

if ! grep -q "^$username:" "$pwdfile" ; then
    echo "$username not found" >&2
    exit 1
fi

if [[ "$2" = "--stdin" ]]; then
    read -r password <&0
else
    for i in seq 3; do
        echo -n "Enter new password: " >&2
        read -rs password
        echo -ne "\nRetype new password: ">&2
        read -rs passcheck
        echo >&2
        if [[ "$password" != "$passcheck" ]]; then
            echo "Error: Passwords don't match!" >&2
        else
            break
        fi
    done
    [[ "$password" = "$passcheck" ]] || exit 1
fi

check_okpassword "$password"

printf -v input '%s\n%s\n' "$password" "$password"
pwdhash="$(doveadm pw -s "$alg" -u "$username" <<< "$input")"
cp "$pwdfile" "$pwdfile~"
sed -E -i "s'^$username:[^:]*:(.*)'$username:$pwdhash:\1'" "$pwdfile"

echo "Password updated"