#!/bin/bash

set -e

username="$1"
if [[ -z "$username" ]]; then
    echo "Usage: email-create <username>" >&2
    exit 1
fi

source "$(dirname "$0")/helpers/common.sh"

thisdir="$(abs `dirname "$0"`)"

alias metaval="$thisdir/helpers/metaval"

pwdfile="$(metaval auth.file)"
gname="$(metaval auth.group)"
alg="$(metaval auth.alg)"
pwopts="$(metaval auth.pwgenopts)"
hdir="$(metaval auth.emaildir)"
shell="$(metaval auth.shell)"
pwlen="32"

homedir="$hdir/$username"

if [[ ! -e "$pwdfile" ]]; then
    touch "$pwdfile" || exit 1
fi

gid="$(grep "^$gname:" /etc/group | awk -F: '{print $3}')"
if [[ -z "$gid" ]]; then
    gid="515"
    echo "Creating group $gname with gid $gid" >&2
    groupadd -g "$gid" "$gname"
fi

if grep -q "^$username:" "$pwdfile" ; then
    echo "User $username already exists" >&2
    exit 1
fi

lastid="$(awk -F: '{print $3":"$4}' "$pwdfile" | grep ":$gid\$" | awk -F: '{print $1}' | sort | tail -n 1)"
if [[ -z "$lastid" ]]; then
    uid="601"
else
    uid="$(expr "$lastid" + 1)"
fi

password="$(pwgen "$pwopts" "$pwlen" 1)"
mkdir -pv "$hdir" >&2

if [[ "$pwdfile" = '/etc/passwd' ]]; then
    echo "Creating system user $username with uid $uid" >&2
    useradd -m -d "$homedir" -g "$gid" -u "$uid" -s "$shell" "$username"
    chpasswd <<< "$username:$password"
else
    echo "Creating passwd-file user $username with uid $uid" >&2
    input="$(echo -ne "$password\n$password\n")"
    pwdhash="$(doveadm pw -s "$alg" <<< "$input")"
    line="$username:$pwdhash:$uid:$gid::$homedir:$shell"
    cp "$pwdfile" "$pwdfile~"
    echo "$line" >> "$pwdfile"
    mkdir -pv "$homedir"
    chown "$uid:$gid" "$homedir"
    passwd_map "$pwdfile"
fi

echo "Password for new user:" >&2
echo "$password"