#!/bin/bash

set -e

source "$(dirname "$0")/helpers/common.sh"

thisdir="$(abs `dirname "$0"`)"
alias metaval="$thisdir/helpers/metaval"
pwdfile="$(metaval auth.dir)/users.passwd"

fail() {
    echo "${cRed}Error$cReset $@" >&2
    exit 1
}
info() {
    echo "$cGreen$uCaret$cReset $@"
}

passwd_map "$pwdfile" > /dev/null
info "Updated users map"

passwd_tlsdb "$pwdfile" > /dev/null
info "Updated users TLS file"