#!/bin/bash

set -e

source "$(dirname "$0")/helpers/common.sh"

thisdir="$(abs `dirname "$0"`)"
alias metaval="$thisdir/helpers/metaval"
pwdfile="$(metaval auth.file)"

fail() {
    echo "${cRed}Error$cReset $@" >&2
    exit 1
}
info() {
    echo "$cGreen$uCaret$cReset $@"
}

passwd_map "$pwdfile" > /dev/null
info "Updated passwd map"

passwd_tlsdb "$pwdfile" > /dev/null
info "Updated TLS db"