#!/bin/bash

set -e

source "$(dirname "$0")/helpers/common.sh"

thisdir="$(abs `dirname "$0"`)"
alias metaval="$thisdir/helpers/metaval"
pwdfile="$(metaval auth.file)"

passwd_map "$pwdfile" > /dev/null
info "Updated passwd map"