#!/bin/bash
source "$(dirname "$0")/helpers/common.sh"
shopt -s expand_aliases
alias logger="/usr/bin/logger -t reconfigure"

if [[ -t 0 ]] && [[ -z "$LOGONLY" ]]; then
    alias write="echo"
else
    alias write="true"
fi

log() {
    local fdn msg pfx
    local priority="$1"
    if [[ "$priority" = err ]]; then
        fdn=2
        pfx="${cRed}ERROR${cReset} "
    else
        fdn=1
    fi
    while read msg ; do
        write "$pfx$msg" >&$fdn
        logger -p "$priority" "$msg"
    done
}

run() {
    {
        _run 2>&1 1>&3 3>&- | log err
    } 3>&1 1>&2 | log notice
}

_run() {
    set -e
    local srcdir="$CONFIG_REPO"
    local thisdir="$(abs `dirname "$0"`)"
    local confdir=`postconf -h config_directory`
    local outdir="$confdir/history/$(date_path)"
    local builddir="$outdir/build"
    local helpers="$thisdir/helpers"
    local builddirq="$(printf '%q' "$builddir")"

    echo "Writing update to $outdir"
    mkdir -p "$builddir"
    pushdq "$builddir"
    # postfix main.cf
    postconf -n | grep -v '^config_directory =' > main.cf.old
    postconf -n -c "$srcdir" | grep -v '^config_directory =' > main.cf.new
    if ! md5cmp master.cf.old master.cf.new ; then
        "$helpers/postfixmain_diff" main.cf.old main.cf.new .
    fi

    # postfix master.cf
    postconf -M | cat "$helpers/mastercfhead.txt" - > master.cf.old
    postconf -M -c "$srcdir" | cat "$helpers/mastercfhead.txt" - > master.cf.new
    if ! md5cmp master.cf.old master.cf.new ; then
        opts="--preserve=timestamps -v"
        local mcfa='postfix_master.apply.sh'
        local mcfr='postfix_master.revert.sh'
        diff master.cf.old master.cf.new | sed 's/^/# /' > "$mcfa"
        diff master.cf.new master.cf.old | sed 's/^/# /' > "$mcfr"
        echo "cd $builddirq && install -v -p -m 0644 \\" | teeq -a "$mcfa" "$mcfr"
        echo "    master.cf.new /etc/postfix/master.cf" >> "$mcfa"
        echo "    master.cf.old /etc/postfix/master.cf" >> "$mcfr"
    fi

    # postfix files
    "$helpers/filesdir_diff" "postfix_files" "$srcdir/files" "$confdir" .

    if is_dovecot; then
        # dovecot.conf
        opts="--preserve=timestamps -bv --suffix=.$(date_path)"
        if ! md5cmp "$srcdir/dovecot.conf" /etc/dovecot/dovecot.conf ; then
            cp "$srcdir/dovecot.conf" dovecot.conf.new
            cp /etc/dovecot/dovecot.conf dovecot.conf.old
            local dcfa="dovecot_dot_conf.apply.sh"
            local dcfr="dovecot_dot_conf.revert.sh"
            diff dovecot.conf.old dovecot.conf.new | sed 's/^/# /' > "$dcfa"
            diff dovecot.conf.new dovecot.conf.old | sed 's/^/# /' > "$dcfr"
            echo "cd $builddirq && install -v -p -m 0644 \\" | teeq -a "$dcfa" "$dcfr"
            echo "    dovecot.conf.new /etc/dovecot/dovecot.conf" >> "$dcfa"
            echo "    dovecot.conf.old /etc/dovecot/dovecot.conf" >> "$dcfr"
        fi
        # dovecot/conf.d files
        "$helpers/filesdir_diff" "dovecot_confd_files" "$srcdir/dovecot" /etc/dovecot/conf.d .
    fi

    popdq

    find "$outdir" -type f -print0 | xargs -0 chmod 0644
    local applyfiles
    readarray -t applyfiles < <(ls "$builddir/"*.apply.sh 2>/dev/null)
    if [[ "${#applyfiles[@]}" = 0 ]]; then
        echo "No configuration changes"
        rm -r "$outdir"
    else
        echo "Building change script"
        local applyfile="$outdir/apply.sh"
        local revertfile="$outdir/revert.sh"
        local header="$(printf "#!/bin/bash\n# $(date)\n# --------------")"
        echo -e "$header\n" | teeq -a "$applyfile" "$revertfile"
        local fa
        local fr
        for fa in "${applyfiles[@]}" ; do
            local fr="$(sed 's/\.apply\.sh$/\.revert\.sh/' <<< "$fa")"
            local ftitle="$(basename $fa | sed 's/\..*//')"
            echo " > $ftitle"
            echo "# $ftitle" >> "$applyfile"| teeq -a "$applyfile" "$revertfile"
            cat "$fa" >> "$applyfile"
            if [[ -e "$fr" ]]; then
                cat "$fr" >> "$revertfile"
            else
                echo "# no revert action" >> "$revertfile"
            fi
            echo "" | teeq -a "$applyfile" "$revertfile"
            rm -f "$fa" "$fr"
        done
        echo "Running change script"
        bash "$applyfile"
        echo "Marking as latest"
        pushdq "$outdir/.."
        rm -f latest
        ln -s "$(basename "$outdir")" latest
        popdq
    fi

    echo "Updating postmaps"
    "$helpers/postmaps_update" "$confdir"

    postfix_reload
    dovecot_reload
}

run