#!/bin/bash
source "$(dirname "$0")/helpers/common.sh"
shopt -s expand_aliases
alias logger="/usr/bin/logger -t reconfigure"

if [[ -t 0 ]] && [[ -z "$LOGONLY" ]]; then
    alias write="echo -e"
else
    alias write="true"
fi

log() {
    local fdn
    local priority="$1"
    local msg
    local pfx
    if [[ "$priority" = err ]]; then
        fdn=2
        pfx="${cRed}ERROR${cReset} "
    else
        fdn=1
    fi
    while read msg ; do
        write "$pfx$msg" >&$fdn
        logger -p "$priority" "$msg"
    done
}

run() {
    {
        _run 2>&1 1>&3 3>&- | log err
    } 3>&1 1>&2 | log notice
}

_run() {
    set -e
    local srcdir="$CONFIG_REPO"
    local thisdir="$(abs `dirname "$0"`)"
    local confdir=`postconf -h config_directory`
    local outdir="$confdir/history/$(date_path)"
    local helpers="$thisdir/helpers"

    echo "Writing update to $outdir"
    mkdir -p "$outdir/tmp"
    postconf -n > "$outdir/tmp/main.old"
    postconf -n -c "$srcdir" > "$outdir/tmp/main.src"
    "$helpers/config_diff" "$outdir/tmp/main.old" "$outdir/tmp/main.src" "$outdir"
    "$helpers/files_diff" "$confdir" "$outdir"

    find "$outdir" -type f -print0 | xargs -0 chmod 0644

    echo "Applying reconfigure"
    ls "$outdir"/*.commit.sh 2>/dev/null | while read f; do
        echo "[apply] $(basename "$f")"
        bash "$f"
    done

    echo "Marking as latest"
    pushdq "$outdir/.."
    rm -f latest
    ln -s "$(basename "$outdir")" latest
    popdq

    echo "Updating postmaps"
    "$helpers/post_maps" "$confdir"

    postfix_reload

    local ischange=
    if is_dovecot ; then
        echo "Updating dovecot config"
        pushdq "$srcdir"
        opts="--preserve=timestamps -bv --suffix=.$(date_path)"
        if ! md5cmp dovecot.conf /etc/dovecot/dovecot.conf ; then
            cp $opts dovecot.conf /etc/dovecot
            ischange=true
        fi
        ls 10-*.conf 2>/dev/null | while read f; do
            if ! md5cmp "$f" "/etc/dovecot/conf.d/$f" ; then
                cp $opts "$f" "/etc/dovecot/conf.d/$f"
                ischange=true
            fi
        done
        popdq
        if [[ ! -z "$ischange" ]]; then
            dovecot_reload
        fi
    fi
}

run